SET search_path = public;

-- Create sports table
CREATE TABLE sports (
    id UUID PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create teams table
CREATE TABLE teams (
    id UUID PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    sport_id UUID REFERENCES sports(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create articles table
CREATE TABLE articles (
    id UUID PRIMARY KEY,
    title TEXT NOT NULL,
    summary_ai TEXT,
    original_url TEXT UNIQUE NOT NULL,
    source_name TEXT NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    team_id UUID REFERENCES teams(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create ephemerides table
CREATE TABLE ephemerides (
    id UUID PRIMARY KEY,
    team_id UUID REFERENCES teams(id) ON DELETE CASCADE,
    importance INTEGER NOT NULL DEFAULT 0,
    content TEXT NOT NULL, -- Assuming content for ephemeris generated by AI
    event_date DATE NOT NULL, -- Date of the historical event
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Optional: Add indexes for foreign keys for performance
CREATE INDEX idx_articles_team_id ON articles(team_id);
CREATE INDEX idx_teams_sport_id ON teams(sport_id);
CREATE INDEX idx_ephemerides_team_id ON ephemerides(team_id);
